import { Dhikr, DhikrCategory } from "@/types";
import { DefaultDhikrColors } from "./colors";

export const DEFAULT_DHIKR_LIST: Dhikr[] = [
  {
    id: "1",
    arabicText: "سبحان الله",
    transliteration: "Subhan Allah",
    translation: "Glory be to Allah",
    count: 0,
    targetCount: 33,
    color: DefaultDhikrColors["سبحان الله"],
    category: "general",
  },
  {
    id: "2",
    arabicText: "الحمد لله",
    transliteration: "Alhamdulillah",
    translation: "Praise be to Allah",
    count: 0,
    targetCount: 33,
    color: DefaultDhikrColors["الحمد لله"],
    category: "general",
  },
  {
    id: "3",
    arabicText: "الله أكبر",
    transliteration: "Allahu Akbar",
    translation: "Allah is the Greatest",
    count: 0,
    targetCount: 33,
    color: DefaultDhikrColors["الله أكبر"],
    category: "general",
  },
  {
    id: "4",
    arabicText: "لا إله إلا الله",
    transliteration: "La ilaha illallah",
    translation: "There is no god but Allah",
    count: 0,
    targetCount: 100,
    color: DefaultDhikrColors["لا إله إلا الله"],
    category: "general",
  },
  {
    id: "5",
    arabicText: "أستغفر الله",
    transliteration: "Astaghfirullah",
    translation: "I seek forgiveness from Allah",
    count: 0,
    targetCount: 100,
    color: DefaultDhikrColors["أستغفر الله"],
    category: "general",
  },
];

export const DHIKR_CATEGORIES: DhikrCategory[] = [
  {
    id: "all",
    name: "All",
    nameArabic: "الكل",
    icon: "sparkles",
  },
  {
    id: "morning",
    name: "Morning",
    nameArabic: "الصباح",
    icon: "sun",
  },
  {
    id: "evening",
    name: "Evening",
    nameArabic: "المساء",
    icon: "moon",
  },
  {
    id: "after-prayer",
    name: "After Prayer",
    nameArabic: "بعد الصلاة",
    icon: "clock",
  },
  {
    id: "sleep",
    name: "Sleep",
    nameArabic: "النوم",
    icon: "moon",
  },
  {
    id: "wakeup",
    name: "Wake Up",
    nameArabic: "الاستيقاظ",
    icon: "sun",
  },
];

export const ADHKAR_LIST = [
  // أذكار الصباح
  {
    id: "morning-1",
    arabicText: "﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾",
    transliteration: "Allahu la ilaha illa Huwa, al-Hayyul-Qayyum. La ta'khudhuhu sinatun wa la nawm. Lahu ma fis-samawati wa ma fil-ard. Man dhal-ladhi yashfa'u 'indahu illa bi-idhnih. Ya'lamu ma bayna aydihim wa ma khalfahum, wa la yuhituna bi-shay'in min 'ilmihi illa bima sha'. Wasi'a Kursiyyuhus-samawati wal-ard, wa la ya'uduhu hifdhuhuma. Wa Huwal-'Aliyyul-'Adhim.",
    translation: "Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence.",
    category: "morning",
  },
  {
    id: "morning-2",
    arabicText: "﴿قُلْ هُوَ اللَّهُ أَحَدٌ * اللَّهُ الصَّمَدُ * لَمْ يَلِدْ وَلَمْ يُولَدْ * وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ﴾\n\n﴿قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ * مِن شَرِّ مَا خَلَقَ * وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ * وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ * وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ﴾\n\n﴿قُلْ أَعُوذُ بِرَبِّ النَّاسِ * مَلِكِ النَّاسِ * إِلَٰهِ النَّاسِ * مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ * الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ * مِنَ الْجِنَّةِ وَالنَّاسِ﴾",
    transliteration: "Qul Huwa Allahu Ahad, Allahus-Samad, Lam yalid wa lam yulad, Wa lam yakun lahu kufuwan ahad. Qul a'udhu bi Rabbil-Falaq... Qul a'udhu bi Rabbin-Nas...",
    translation: "The three Quls: Surah Al-Ikhlas, Al-Falaq, and An-Nas.",
    category: "morning",
  },
  {
    id: "morning-3",
    arabicText: "أصبحنا وأصبح الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير. رب أسألك خير ما في هذا اليوم وخير ما بعده، وأعوذ بك من شر ما في هذا اليوم وشر ما بعده، رب أعوذ بك من الكسل وسوء الكِبَر، رب أعوذ بك من عذاب في النار وعذاب في القبر.",
    transliteration: "Asbahna wa asbahal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd wa huwa 'ala kulli shay'in qadir. Rabbi as'aluka khayra ma fi hadhal-yawm wa khayra ma ba'dah, wa a'udhu bika min sharri ma fi hadhal-yawm wa sharri ma ba'dah.",
    translation: "We have entered the morning and the sovereignty has entered to Allah.",
    category: "morning",
  },
  {
    id: "morning-4",
    arabicText: "اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت، أعوذ بك من شر ما صنعت، أبوء لك بنعمتك عليَّ، وأبوء بذنبي، فاغفر لي فإنه لا يغفر الذنوب إلا أنت.",
    transliteration: "Allahumma anta Rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bi-ni'matika 'alayy, wa abu'u bi-dhanbi, faghfir li fa-innahu la yaghfirudh-dhunuba illa ant.",
    translation: "O Allah, You are my Lord. There is no god but You. You created me and I am Your servant.",
    category: "morning",
  },
  {
    id: "morning-5",
    arabicText: "رضيت بالله ربًا، وبالإسلام دينًا، وبمحمد ﷺ نبيًا.",
    transliteration: "Raditu billahi Rabban, wa bil-Islami dinan, wa bi-Muhammadin ﷺ nabiyyan. (3 مرات)",
    translation: "I am pleased with Allah as Lord, with Islam as religion, and with Muhammad as Prophet.",
    category: "morning",
  },
  {
    id: "morning-6",
    arabicText: "يا حي يا قيوم برحمتك أستغيث، أصلح لي شأني كله، ولا تكلني إلى نفسي طرفة عين.",
    transliteration: "Ya Hayyu ya Qayyum, bi-rahmatika astaghith, aslih li sha'ni kullah, wa la takilni ila nafsi tarfata 'ayn.",
    translation: "O Ever-Living, O Sustainer, by Your mercy I call upon You to set right all my affairs.",
    category: "morning",
  },
  {
    id: "morning-7",
    arabicText: "اللهم ما أصبح بي من نعمة أو بأحدٍ من خلقك فمنك وحدك لا شريك لك، فلك الحمد ولك الشكر.",
    transliteration: "Allahumma ma asbaha bi min ni'matin aw bi-ahadin min khalqik fa-minka wahdaka la sharika lak, fa-lakal-hamdu wa lakash-shukr.",
    translation: "O Allah, whatever blessing has been received by me or anyone of Your creation is from You alone.",
    category: "morning",
  },
  {
    id: "morning-8",
    arabicText: "اللهم إني أصبحت أشهدك وأشهد حملة عرشك وملائكتك وجميع خلقك، أنك أنت الله لا إله إلا أنت وحدك لا شريك لك، وأن محمدًا عبدك ورسولك.",
    transliteration: "Allahumma inni asbahtu ushhiduka wa ushhidu hamalata 'arshika wa mala'ikataka wa jami'a khalqik, annaka Antallahu la ilaha illa anta wahdaka la sharika lak, wa anna Muhammadan 'abduka wa rasuluk. (4 مرات)",
    translation: "O Allah, I have entered the morning and call upon You and the carriers of Your Throne to witness.",
    category: "morning",
  },
  {
    id: "morning-9",
    arabicText: "حسبي الله لا إله إلا هو عليه توكلت وهو رب العرش العظيم.",
    transliteration: "Hasbiyallahu la ilaha illa Huwa 'alayhi tawakkalt wa Huwa Rabbul-'Arshil-'Adhim. (7 مرات)",
    translation: "Allah is sufficient for me. There is none worthy of worship but He. I have placed my trust in Him.",
    category: "morning",
  },
  {
    id: "morning-10",
    arabicText: "بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم.",
    transliteration: "Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama', wa Huwas-Sami'ul-'Alim. (3 مرات)",
    translation: "In the Name of Allah, with Whose Name nothing can harm in the earth nor in the heaven.",
    category: "morning",
  },
  {
    id: "morning-11",
    arabicText: "أعوذ بكلمات الله التامات من شر ما خلق.",
    transliteration: "A'udhu bi-kalimatillahit-tammati min sharri ma khalaq. (3 مرات)",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    category: "morning",
  },
  {
    id: "morning-12",
    arabicText: "اللهم إني أسألك علمًا نافعًا، ورزقًا طيبًا، وعملاً متقبلًا.",
    transliteration: "Allahumma inni as'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbalan.",
    translation: "O Allah, I ask You for beneficial knowledge, goodly provision, and accepted deeds.",
    category: "morning",
  },
  {
    id: "morning-13",
    arabicText: "أستغفر الله وأتوب إليه.",
    transliteration: "Astaghfirullaha wa atubu ilayh. (100 مرة)",
    translation: "I seek forgiveness from Allah and repent to Him.",
    category: "morning",
  },
  {
    id: "morning-14",
    arabicText: "سبحان الله وبحمده.",
    transliteration: "Subhanallahi wa bihamdihi. (100 مرة)",
    translation: "Glory is to Allah and praise is to Him.",
    category: "morning",
  },
  {
    id: "morning-15",
    arabicText: "اللَّهُمَّ عَالِمَ الْغَيْبِ وَالشَّهَادَةِ فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ رَبَّ كُلِّ شَيْءٍ وَمَلِيكَهُ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ، أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي وَمِنْ شَرِّ الشَّيْطَانِ وَشِرْكِهِ.",
    transliteration: "Allahumma 'alimal-ghaybi wash-shahadati fatiras-samawati wal-ard, rabba kulli shay'in wa malikah, ashhadu an la ilaha illa ant, a'udhu bika min sharri nafsi wa min sharrish-shaytani wa shirkihi.",
    translation: "O Allah, Knower of the unseen and the witnessed, Creator of the heavens and the earth.",
    category: "morning",
  },
  
  // أذكار المساء
  {
    id: "evening-1",
    arabicText: "﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾",
    transliteration: "Allahu la ilaha illa Huwa, al-Hayyul-Qayyum. La ta'khudhuhu sinatun wa la nawm. Lahu ma fis-samawati wa ma fil-ard. Man dhal-ladhi yashfa'u 'indahu illa bi-idhnih. Ya'lamu ma bayna aydihim wa ma khalfahum, wa la yuhituna bi-shay'in min 'ilmihi illa bima sha'. Wasi'a Kursiyyuhus-samawati wal-ard, wa la ya'uduhu hifdhuhuma. Wa Huwal-'Aliyyul-'Adhim.",
    translation: "Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence.",
    category: "evening",
  },
  {
    id: "evening-2",
    arabicText: "﴿قُلْ هُوَ اللَّهُ أَحَدٌ * اللَّهُ الصَّمَدُ * لَمْ يَلِدْ وَلَمْ يُولَدْ * وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ﴾\n\n﴿قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ * مِن شَرِّ مَا خَلَقَ * وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ * وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ * وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ﴾\n\n﴿قُلْ أَعُوذُ بِرَبِّ النَّاسِ * مَلِكِ النَّاسِ * إِلَٰهِ النَّاسِ * مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ * الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ * مِنَ الْجِنَّةِ وَالنَّاسِ﴾",
    transliteration: "Qul Huwa Allahu Ahad, Allahus-Samad, Lam yalid wa lam yulad, Wa lam yakun lahu kufuwan ahad. Qul a'udhu bi Rabbil-Falaq... Qul a'udhu bi Rabbin-Nas...",
    translation: "The three Quls: Surah Al-Ikhlas, Al-Falaq, and An-Nas.",
    category: "evening",
  },
  {
    id: "evening-3",
    arabicText: "أمسينا وأمسى الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير. رب أسألك خير ما في هذه الليلة وخير ما بعدها، وأعوذ بك من شر ما في هذه الليلة وشر ما بعدها، رب أعوذ بك من الكسل وسوء الكِبَر، رب أعوذ بك من عذاب في النار وعذاب في القبر.",
    transliteration: "Amsayna wa amsal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd wa huwa 'ala kulli shay'in qadir. Rabbi as'aluka khayra ma fi hadhihil-laylah wa khayra ma ba'daha, wa a'udhu bika min sharri ma fi hadhihil-laylah wa sharri ma ba'daha.",
    translation: "We have entered the evening and the sovereignty has entered to Allah.",
    category: "evening",
  },
  {
    id: "evening-4",
    arabicText: "اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت، أعوذ بك من شر ما صنعت، أبوء لك بنعمتك عليَّ وأبوء بذنبي، فاغفر لي فإنه لا يغفر الذنوب إلا أنت.",
    transliteration: "Allahumma anta Rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bi-ni'matika 'alayy, wa abu'u bi-dhanbi, faghfir li fa-innahu la yaghfirudh-dhunuba illa ant.",
    translation: "O Allah, You are my Lord. There is no god but You. You created me and I am Your servant.",
    category: "evening",
  },
  {
    id: "evening-5",
    arabicText: "رضيت بالله ربًا، وبالإسلام دينًا، وبمحمد ﷺ نبيًا.",
    transliteration: "Raditu billahi Rabban, wa bil-Islami dinan, wa bi-Muhammadin ﷺ nabiyyan. (3 مرات)",
    translation: "I am pleased with Allah as Lord, with Islam as religion, and with Muhammad as Prophet.",
    category: "evening",
  },
  {
    id: "evening-6",
    arabicText: "يا حي يا قيوم برحمتك أستغيث، أصلح لي شأني كله، ولا تكلني إلى نفسي طرفة عين.",
    transliteration: "Ya Hayyu ya Qayyum, bi-rahmatika astaghith, aslih li sha'ni kullah, wa la takilni ila nafsi tarfata 'ayn.",
    translation: "O Ever-Living, O Sustainer, by Your mercy I call upon You to set right all my affairs.",
    category: "evening",
  },
  {
    id: "evening-7",
    arabicText: "اللهم ما أمسى بي من نعمة أو بأحدٍ من خلقك فمنك وحدك لا شريك لك، فلك الحمد ولك الشكر.",
    transliteration: "Allahumma ma amsa bi min ni'matin aw bi-ahadin min khalqik fa-minka wahdaka la sharika lak, fa-lakal-hamdu wa lakash-shukr.",
    translation: "O Allah, whatever blessing has been received by me or anyone of Your creation is from You alone.",
    category: "evening",
  },
  {
    id: "evening-8",
    arabicText: "اللهم إني أمسيت أشهدك وأشهد حملة عرشك وملائكتك وجميع خلقك، أنك أنت الله لا إله إلا أنت وحدك لا شريك لك، وأن محمدًا عبدك ورسولك.",
    transliteration: "Allahumma inni amsaytu ushhiduka wa ushhidu hamalata 'arshika wa mala'ikataka wa jami'a khalqik, annaka Antallahu la ilaha illa anta wahdaka la sharika lak, wa anna Muhammadan 'abduka wa rasuluk. (4 مرات)",
    translation: "O Allah, I have entered the evening and call upon You and the carriers of Your Throne to witness.",
    category: "evening",
  },
  {
    id: "evening-9",
    arabicText: "حسبي الله لا إله إلا هو عليه توكلت وهو رب العرش العظيم.",
    transliteration: "Hasbiyallahu la ilaha illa Huwa 'alayhi tawakkalt wa Huwa Rabbul-'Arshil-'Adhim. (7 مرات)",
    translation: "Allah is sufficient for me. There is none worthy of worship but He. I have placed my trust in Him.",
    category: "evening",
  },
  {
    id: "evening-10",
    arabicText: "بسم الله الذي لا يضر مع اسمه شيء في الأرض ولا في السماء وهو السميع العليم.",
    transliteration: "Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama', wa Huwas-Sami'ul-'Alim. (3 مرات)",
    translation: "In the Name of Allah, with Whose Name nothing can harm in the earth nor in the heaven.",
    category: "evening",
  },
  {
    id: "evening-11",
    arabicText: "أعوذ بكلمات الله التامات من شر ما خلق.",
    transliteration: "A'udhu bi-kalimatillahit-tammati min sharri ma khalaq. (3 مرات)",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    category: "evening",
  },
  {
    id: "evening-12",
    arabicText: "اللهم إني أسألك العفو والعافية في ديني ودنياي وأهلي ومالي، اللهم استر عوراتي وآمن روعاتي، واحفظني من بين يدي ومن خلفي، وعن يميني وعن شمالي، ومن فوقي، وأعوذ بعظمتك أن أُغتال من تحتي.",
    transliteration: "Allahumma inni as'alukal-'afwa wal-'afiyata fi dini wa dunyaya wa ahli wa mali, Allahummastir 'awrati wa amin raw'ati, wahfadhni min bayni yadayya wa min khalfi, wa 'an yamini wa 'an shimali, wa min fawqi, wa a'udhu bi-'adhamatika an ughtala min tahti.",
    translation: "O Allah, I ask You for pardon and well-being in my religion, my worldly affairs, my family and my wealth.",
    category: "evening",
  },
  {
    id: "evening-13",
    arabicText: "اللهم إني أسألك علمًا نافعًا، ورزقًا طيبًا، وعملاً متقبلًا.",
    transliteration: "Allahumma inni as'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbalan.",
    translation: "O Allah, I ask You for beneficial knowledge, goodly provision, and accepted deeds.",
    category: "evening",
  },
  {
    id: "evening-14",
    arabicText: "أستغفر الله وأتوب إليه.",
    transliteration: "Astaghfirullaha wa atubu ilayh. (100 مرة)",
    translation: "I seek forgiveness from Allah and repent to Him.",
    category: "evening",
  },
  {
    id: "evening-15",
    arabicText: "سبحان الله وبحمده.",
    transliteration: "Subhanallahi wa bihamdihi. (100 مرة)",
    translation: "Glory is to Allah and praise is to Him.",
    category: "evening",
  },
  
  
  // أذكار بعد الصلاة
  {
    id: "after-prayer-1",
    arabicText: "أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
    transliteration: "Astaghfirullah, astaghfirullah, astaghfirullah. Allahumma antas-salamu wa minkas-salam",
    translation: "I seek Allah's forgiveness (3 times). O Allah, You are As-Salam and from You is all peace, blessed are You, O Possessor of majesty and honor",
    category: "after-prayer",
  },
  {
    id: "after-prayer-2",
    arabicText: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، اللَّهُمَّ لَا مَانِعَ لِمَا أَعْطَيْتَ، وَلَا مُعْطِيَ لِمَا مَنَعْتَ، وَلَا يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ",
    transliteration: "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir",
    translation: "None has the right to be worshipped except Allah, alone, without partner, to Him belongs all sovereignty and praise and He is over all things omnipotent",
    category: "after-prayer",
  },
  {
    id: "after-prayer-3",
    arabicText: "سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَاللَّهُ أَكْبَرُ",
    transliteration: "Subhanallah, walhamdulillah, wallahu akbar",
    translation: "Glory is to Allah, and praise is to Allah, and Allah is the greatest",
    category: "after-prayer",
  },
 
  // أدعية عامة
  {
    id: "dua-1",
    arabicText: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    transliteration: "Rabbana atina fid-dunya hasanah wa fil-akhirati hasanah wa qina 'adhab an-nar",
    translation: "Our Lord, give us in this world good and in the Hereafter good and protect us from the punishment of the Fire",
    category: "duas",
  },
  {
    id: "dua-2",
    arabicText: "رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    transliteration: "Rabbi ighfir li waliwalidayya warhamhuma kama rabbayani saghira",
    translation: "My Lord, forgive me and my parents, and have mercy upon them as they brought me up when I was small",
    category: "duas",
  },
  {
    id: "dua-3",
    arabicText: "اللَّهُمَّ إِنَّا نَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا",
    transliteration: "Allahumma inna nas'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbalan",
    translation: "O Allah, we ask You for beneficial knowledge, good provision, and accepted deeds",
    category: "duas",
  },
  {
    id: "dua-4",
    arabicText: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ العَفْوَ فَاعْفُ عَنَّا",
    transliteration: "Allahumma innaka 'afuwwun tuhibbul-'afwa fa'fu 'anna",
    translation: "O Allah, You are Pardoning and You love to pardon, so pardon us",
    category: "duas",
  },
  
  // أذكار النوم
  {
    id: "sleep-1",
    arabicText: "بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ، فَإِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا، وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ",
    transliteration: "Bismika Rabbi wada'tu janbi, wa bika arfa'uhu, fa-in amsakta nafsi farhamha, wa in arsaltaha fahfadh-ha bima tahfadhu bihi 'ibadakas-salihin.",
    translation: "In Your name my Lord, I lie down and in Your name I rise, so if You should take my soul then have mercy upon it, and if You should return my soul then protect it in the manner You do so with Your righteous servants.",
    category: "sleep",
  },
  {
    id: "sleep-2",
    arabicText: "اللَّهُمَّ إِنَّكَ خَلَقْتَ نَفْسِي وَأَنْتَ تَوَفَّاهَا، لَكَ مَمَاتُهَا وَمَحْيَاهَا، إِنْ أَحْيَيْتَهَا فَاحْفَظْهَا، وَإِنْ أَمَتَّهَا فَاغْفِرْ لَهَا، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ",
    transliteration: "Allahumma innaka khalaqta nafsi wa anta tawaffaha, laka mamatuha wa mahyaha, in ahyaytaha fahfadh-ha, wa in amattaha faghfir laha. Allahumma inni as'alukal-'afiyah.",
    translation: "O Allah, verily You have created my soul and You shall take its life, to You belongs its life and death. If You should keep my soul alive then protect it, and if You should take its life then forgive it. O Allah, I ask You for well-being.",
    category: "sleep",
  },
  {
    id: "sleep-3",
    arabicText: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
    transliteration: "Allahumma qini 'adhabaka yawma tab'athu 'ibadak. (3 مرات)",
    translation: "O Allah, protect me from Your punishment on the day Your servants are resurrected. (3 times)",
    category: "sleep",
  },
  {
    id: "sleep-4",
    arabicText: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration: "Bismika Allahumma amutu wa ahya.",
    translation: "In Your name O Allah, I live and die.",
    category: "sleep",
  },
  {
    id: "sleep-5",
    arabicText: "سُبْحَانَكَ اللَّهُمَّ رَبِّي بِكَ وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ، إِنْ أَمْسَكْتَ نَفْسِي فَاغْفِرْ لَهَا، وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ",
    transliteration: "Subhanaka Allahumma Rabbi bika wada'tu janbi, wa bika arfa'uhu, in amsakta nafsi faghfir laha, wa in arsaltaha fahfadh-ha bima tahfadhu bihi 'ibadakas-salihin.",
    translation: "Glory be to You O Allah, my Lord. With Your name I lay myself down and with Your name I rise. If You take my soul, forgive it, and if You send it back, protect it as You protect Your righteous servants.",
    category: "sleep",
  },
  {
    id: "sleep-6",
    arabicText: "اللَّهُمَّ بِاسْمِكَ أَحْيَا وَأَمُوتُ",
    transliteration: "Allahumma bismika ahya wa amut.",
    translation: "O Allah, in Your name I live and die.",
    category: "sleep",
  },
  {
    id: "sleep-7",
    arabicText: "﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾",
    transliteration: "Ayat al-Kursi: Allahu la ilaha illa Huwa, al-Hayyul-Qayyum...",
    translation: "The Verse of the Throne: Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence...",
    category: "sleep",
  },
  {
    id: "sleep-8",
    arabicText: "﴿آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِ ۚ وَقَالُوا سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ﴾",
    transliteration: "Amana ar-Rasulu bima unzila ilayhi min Rabbihi wal-mu'minun...",
    translation: "The Messenger has believed in what was revealed to him from his Lord, and [so have] the believers...",
    category: "sleep",
  },
  {
    id: "sleep-9",
    arabicText: "اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ، لَا مَلْجَأَ وَلَا مَنْجَا مِنْكَ إِلَّا إِلَيْكَ، آمَنْتُ بِكِتَابِكَ الَّذِي أَنْزَلْتَ، وَبِنَبِيِّكَ الَّذِي أَرْسَلْتَ",
    transliteration: "Allahumma aslamtu nafsi ilayk, wa fawwadtu amri ilayk, wa wajjahtu wajhi ilayk, wa alja'tu dhahri ilayk, raghbatan wa rahbatan ilayk. La malja'a wa la manja minka illa ilayk. Amantu bikitabika alladhi anzalt, wa nabiyyika alladhi arsalt.",
    translation: "O Allah, I submit my soul to You, I entrust my affair to You, I turn my face to You, and I rely completely upon You, out of hope in You and fear of You. There is no refuge nor escape from You except to You. I believe in Your Book which You have revealed, and in Your Prophet whom You have sent.",
    category: "sleep",
  },
  {
    id: "sleep-10",
    arabicText: "سُبْحَانَ اللَّهِ (33 مرة)، الْحَمْدُ لِلَّهِ (33 مرة)، اللَّهُ أَكْبَرُ (34 مرة)",
    transliteration: "Subhan Allah (33), Alhamdulillah (33), Allahu Akbar (34)",
    translation: "Glory be to Allah (33 times), Praise be to Allah (33 times), Allah is the Greatest (34 times)",
    category: "sleep",
  },

  // أذكار الاستيقاظ
  {
    id: "wakeup-1",
    arabicText: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    transliteration: "Alhamdulillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur.",
    translation: "Praise is to Allah who gave us life after having taken it from us and unto Him is the resurrection.",
    category: "wakeup",
  },
  {
    id: "wakeup-2",
    arabicText: "الْحَمْدُ لِلَّهِ الَّذِي عَافَانِي فِي جَسَدِي، وَرَدَّ عَلَيَّ رُوحِي، وَأَذِنَ لِي بِذِكْرِهِ",
    transliteration: "Alhamdulillahil-ladhi 'afani fi jasadi, wa radda 'alayya ruhi, wa adhina li bidhikrih.",
    translation: "Praise is to Allah Who gave strength to my body, returned my soul to me, and permitted me to remember Him.",
    category: "wakeup",
  },
  {
    id: "wakeup-3",
    arabicText: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَلَا إِلَهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ. رَبِّ اغْفِرْ لِي",
    transliteration: "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd, wa Huwa 'ala kulli shay'in Qadir. Subhanallah, walhamdulillah, wa la ilaha illallah, wallahu Akbar, wa la hawla wa la quwwata illa billahil-'Aliyyil-'Adhim. Rabbighfir li.",
    translation: "None has the right to be worshipped except Allah, alone without partner, to Him belongs sovereignty and praise and He is over all things wholly capable. How perfect Allah is, and all praise is for Allah, and none has the right to be worshipped except Allah, and Allah is the greatest, and there is no power nor might except with Allah, The Most High, The Supreme. My Lord, forgive me.",
    category: "wakeup",
  },
  {
    id: "wakeup-4",
    arabicText: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لَا إِلَهَ إِلَّا أَنْتَ",
    transliteration: "Allahumma inni a'udhu bika minal-kufri wal-faqr, wa a'udhu bika min 'adhabil-qabr, la ilaha illa ant.",
    translation: "O Allah, I seek refuge in You from disbelief and poverty, and I seek refuge in You from the punishment of the grave. None has the right to be worshipped except You.",
    category: "wakeup",
  },
  {
    id: "wakeup-5",
    arabicText: "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ",
    transliteration: "Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namut, wa ilaykan-nushur.",
    translation: "O Allah, by You we enter the morning, by You we enter the evening, by You we live, and by You we die, and to You is the resurrection.",
    category: "wakeup",
  },
  {
    id: "wakeup-6",
    arabicText: "أَصْبَحْنَا عَلَى فِطْرَةِ الْإِسْلَامِ، وَعَلَى كَلِمَةِ الْإِخْلَاصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِينَا إِبْرَاهِيمَ، حَنِيفًا مُسْلِمًا، وَمَا كَانَ مِنَ الْمُشْرِكِينَ",
    transliteration: "Asbahna 'ala fitratil-Islam, wa 'ala kalimatil-ikhlas, wa 'ala dini nabiyyina Muhammadin sallallahu 'alayhi wa sallam, wa 'ala millati abina Ibrahim, hanifan musliman, wa ma kana minal-mushrikin.",
    translation: "We rise upon the fitrah of Islam, and the word of pure faith, and upon the religion of our Prophet Muhammad and the religion of our forefather Ibrahim, who was a Muslim and of true faith and was not of those who associate others with Allah.",
    category: "wakeup",
  },
];